### ISSUE TITLE
Publish binaries

### ISSUE THREAD

**Issue by JaRoSchm** [WGUNDERWOOD/tex-fmt#12]
Hi, it would be helpful if tex-fmt would publish binaries for every release using CI. As an example you can look at texlab‘s GitHub releases. Not everyone using latex is also using rust and therefore has cargo installed.

**Comment by WGUNDERWOOD** [comment]
Thanks, I will look into this!

**Comment by JaRoSchm** [comment]
Thank you!

**Comment by WGUNDERWOOD** [comment]
Fixed in ac68d128b792d51cc17303be1c96dd31e838d672 (release v0.4.1). Note that the resulting executables are dynamically linked (so for example they do not work on NixOS).

**Comment by JaRoSchm** [comment]
Thank you, works perfectly for me!
