### ISSUE TITLE
File extension should be optional

### ISSUE THREAD

**Issue by VictorEijkhout** [WGUNDERWOOD/tex-fmt#15]
Current latex engines take

```
pdflatex myfile
```

without the `.tex` extension. I'd appreciate a similar behavior.

**Comment by WGUNDERWOOD** [comment]
Thanks, I will think about how best to handle it. I understand that the file extension should not be essential, but it can help prevent typos on the command line. Maybe we can raise a warning instead of an error?

**Comment by WGUNDERWOOD** [comment]
To help me understand this better, suppose files `main.tex` and `main.bib` both exist. What should be the outcome of running `tex-fmt main`? This seems different from `pdflatex main`, which is clearly defined as operating on the `.tex` file.

**Comment by WGUNDERWOOD** [comment]
This has been implemented in 5197c7c559a76ab3a6f5e681dace30d3035fa3b9. Please let me know if it has the desired behaviour.
