### ISSUE TITLE
tex-fmt-x86_64-windows detected as Ransomware 

### ISSUE THREAD

**Issue by julian-belina** [WGUNDERWOOD/tex-fmt#33]
Hello, 

unfotunetly the tex-fmt-x86_64-windows binary is detected as ransomware by my antivirus software "TREND Apex One Security Agent ". I am not sure if there is anything that can be done about this, but I wanted to report this in case it can be prevented.

**Comment by WGUNDERWOOD** [comment]
Thank you for letting me know. I do not have any experience with this antivirus software, but perhaps there is an option to mark tex-fmt as safe within the software?
