### ISSUE TITLE
[Rust] Correct use of the `exit()` function?

### ISSUE THREAD

**Issue by cdesaintguilhem** [WGUNDERWOOD/tex-fmt#34]
I have a question about the following lines in `src/main.rs`:

https://github.com/WGUNDERWOOD/tex-fmt/blob/5fd1380ac7608403a3cc417679bdcd7959c7a3e6/src/main.rs#L76-L77

The documentation for `std::process::exit()` says "Note that because this function never returns, and that it terminates the process, no destructors on the current stack or any other thread's stack will be run." What does this imply about `logs` which is allocated at line 49 and never leaves the scope of the main function before `exit()` is called? Is the `Vec` never destroyed?

**Comment by WGUNDERWOOD** [comment]
Thanks for pointing this out. Perhaps we should instead be returning a `std::process::ExitCode`? I will read more about this and get back to you.

**Comment by WGUNDERWOOD** [comment]
Implemented in 59e9636b363f1952b71660718868caedd7a72c62.
