### ISSUE TITLE
Check option

### ISSUE THREAD

**Issue by alexarice** [WGUNDERWOOD/tex-fmt#4]
Formatters commonly have an option to check that a file is already formatted, and not change it if it isn't. This could be useful here, as the debug information could be useful without modifying the file. The downside to this is that I believe the debug messages use the new line numbers, so would likely be in the wrong place on a dry run

**Comment by WGUNDERWOOD** [comment]
Yes, line numbers would be in the wrong place in the log messages. However it's probably still worth having a `--check` option which exits with an error if the file is not formatted correctly, for use in git hooks etc

**Comment by WGUNDERWOOD** [comment]
This has been implemented in f183232ab4d81f602a52a577cd538f9ae8d5fa51.
Let me know if it works as expected.

**Comment by alexarice** [comment]
Seems to work
