### ISSUE TITLE
[docs] add configuration usage

### ISSUE THREAD

**Issue by marcfranquesa** [WGUNDERWOOD/tex-fmt#46]
First of all, thank you! I found this formatter recently and I am really liking it.

I think it would be nice to add documentation on the available flags to change the settings (i.e. --tab 4). Also relating to [this issue](https://github.com/WGUNDERWOOD/tex-fmt/issues/39), when the config file is implemented to document the usage. Could be a section added to the README? I can start up an initial draft.

Also opened a [PR](https://github.com/mason-org/mason-registry/pull/7595) to include tex-fmt in the [Mason](https://github.com/williamboman/mason.nvim) registry, hope that is ok!

**Comment by WGUNDERWOOD** [comment]
Now that tex-fmt is becoming a little more complex, I think this is a good idea! Perhaps we can keep the "Usage" section in the README as it is now, containing just the most useful flags. We can then add a new section called "Options" at the very bottom of the README, documenting each flag in more detail. Feel free to make a draft PR and I can take a look.
