### ISSUE TITLE
[feature] add shell-completions

### ISSUE THREAD

**Issue by werdahias** [WGUNDERWOOD/tex-fmt#57]
shell completions would be really nice to have. You could look into clap-completion to generate them dynamically.

**Comment by WGUNDERWOOD** [comment]
Thanks, I'll look into doing this.

**Comment by WGUNDERWOOD** [comment]
Implemented in 7af166dff01e1d368cc80edf6b204a1beee328a0. Let me know if you are able to test this, as I have only tried it with bash.

**Comment by cdesaintguilhem** [comment]
Just reporting that they work for `zsh` on macOS for me. Thanks to you both for suggesting and implementing this!
