### ISSUE TITLE
Formatting directory fails

### ISSUE THREAD

**Issue by cyb3rko** [WGUNDERWOOD/tex-fmt#63]
Thanks for this project.

I currently use it via the LaTeX Workshop extension in VS Code for formatting my thesis.  
It worked fine, but after returning to the project again, the formatter fails.

Calling it manually from the CLI for one file does work well, but calling it on a directory does fail:

```
RUST_BACKTRACE=full tex-fmt .
thread 'main' panicked at src/logging.rs:166:22:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:        0x1041ceaf4 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h2260af3a60e707d0
   1:        0x1041e7794 - core::fmt::write::h40c2acd4666eb4d3
   2:        0x1041da670 - std::io::Write::write_fmt::h41d6e98dca6ecc3d
   3:        0x1041ce9a8 - std::sys::backtrace::BacktraceLock::print::h6927682eb47cb165
   4:        0x1041c5d74 - std::panicking::default_hook::{{closure}}::h3800acb1d5aa9da8
   5:        0x1041c5c1c - std::panicking::default_hook::hdb07ba29d8151fe7
   6:        0x1041c6378 - std::panicking::rust_panic_with_hook::h3a42c361c08813d5
   7:        0x1041ceee0 - std::panicking::begin_panic_handler::{{closure}}::h483101861bc4cead
   8:        0x1041ced4c - std::sys::backtrace::__rust_end_short_backtrace::he99aa938f9475e2a
   9:        0x1041c5e04 - _rust_begin_unwind
  10:        0x1041fa560 - core::panicking::panic_fmt::h5a90ea35d2c8d236
  11:        0x1041fa5d0 - core::panicking::panic::h9889520f556572c5
  12:        0x1041fa8b0 - core::option::unwrap_failed::hebd07d0ecc3a97f2
  13:        0x10409a6d0 - tex_fmt::main::h49aa71125074c02e
  14:        0x1040832fc - std::sys::backtrace::__rust_begin_short_backtrace::h2ad41589d3f473ab
  15:        0x1040832e4 - std::rt::lang_start::{{closure}}::h2548be876adffe56
  16:        0x1041beda8 - std::rt::lang_start_internal::hadea728b8c40134b
  17:        0x10409b1cc - _main
```

---

I suppose the LaTeX Workshop does the same thing, hence failing as well

**Comment by cdesaintguilhem** [comment]
I also use tex-fmt via the Latex Workshop extension for VS Code, but I don't believe it passes a directory name. I think it uses the `--stdin` flag to pass the file's content. 

The thing is that v0.5.0 of tex-fmt changed some of the CLI flags that it accepts, so if your extension settings are still configured to use older flags, this could be causing the formatting failure. If you search for "tex-fmt" in the VS Code settings, you should see it come up.

**Comment by WGUNDERWOOD** [comment]
Thanks for this @cyb3rko! tex-fmt does not currently support directory formatting, but this is something I could look into implementing if people are interested. I would want to answer a few questions first, though:

1) What is the desired behaviour? Should tex-fmt act on every file in the directory with an appropriate file suffix? If so, which suffixes? Should it act recursively into subdirectories? How should symlinks be resolved?

2) How can we make this safe to avoid formatting files unexpectedly?

**Comment by cyb3rko** [comment]
> I think it uses the `--stdin` flag to pass the file's content.
> 
> The thing is that v0.5.0 of tex-fmt changed some of the CLI flags that it accepts, so if your extension settings are still configured to use older flags, this could be causing the formatting failure. If you search for "tex-fmt" in the VS Code settings, you should see it come up.

@cdesaintguilhem Thanks, you're right.  
It uses the `--stdin` flag by default and adds the pre-defined `--keep` flag, which was now renamed to `--nowrap` in [0.5.0](https://github.com/WGUNDERWOOD/tex-fmt/releases/tag/v0.5.0). Works again :)

**Comment by cyb3rko** [comment]
> tex-fmt does not currently support directory formatting, but this is something I could look into implementing if people are interested.

@WGUNDERWOOD Well, I guess I never realized it's for single files only as I use VS Code for whole projects and manual calls only for a single `.tex` file.

From my side I'm not requesting a feature to be able to pass directories, my use cases are covered

**Comment by tholop** [comment]
> Thanks for this [@cyb3rko](https://github.com/cyb3rko)! tex-fmt does not currently support directory formatting, but this is something I could look into implementing if people are interested. I would want to answer a few questions first, though:
> 
>     1. What is the desired behaviour? Should tex-fmt act on every file in the directory with an appropriate file suffix? If so, which suffixes? Should it act recursively into subdirectories? How should symlinks be resolved?
> 
>     2. How can we make this safe to avoid formatting files unexpectedly?

@WGUNDERWOOD I just wanted to say that directory formatting is something I would be interested in. To answer some of your questions, in my use case I run recursively on all the files ending in .tex and .bib. I'm not sure about symlinks, and how this could format files unexpectedly. For now I've just been using a Nushell script like:
```
fd -e tex -e bib | lines | each {|file| tex-fmt $file --nowrap }
```

Happy to track this in another issue!
